# action.yaml
name: 'dbt-gloss'
description: 'List of pre-commit hooks to ensure the quality of your dbt projects.'
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  args:
    description: 'pre-commit args'
    required: false
    default: 'run --all-files'

jobs:
  run_pre_commit:
  runs-on: ubuntu-latest
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pre-commit and dbt
      runs: |
        pip install --no-cache-dir pre-commit==2.18.0 \
          dbt-core==1.0.0 \
          dbt-postgres==1.0.0 \
          dbt-redshift==1.0.0 \
          dbt-snowflake==1.0.0 \
          dbt-bigquery==1.0.0
        pre-commit install-hooks

    - name: Run pre-commit hooks
      runs: pre-commit "${{ inputs.args}}"
